### ISSUE TITLE
UnicodeDecodeError in setup.py / setup_win.bat

### ISSUE THREAD

**Issue by z25clp** [textext/textext#101]

**Comment by z25clp** [comment]
I have a problem with the Textex extension for inkscape. 

First I used Textext 0.8.2,. The extension works, however the generated latex text does not appears in the inkscape document. How to solve that problem?

Second, I download "TexText-Windows-0.9.0.zip", I extract the package and I run setup-win.bat the last two lines that appear are:
  File "extension\textext/requirements_check.py", line 613, in find_pstoedit
    first_stderr_line = stderr.decode("utf-8").split("\n")[0]
  File "C:\Program Files\Inkscape\lib\python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 241: invalid continuation byte

I undestant that a problem exits however I don't know how to solve it. Any help?

**Comment by sizmailov** [comment]
Thanks for the report!

Output of `pstoedit` on your system turned out to be non-utf8. At the moment I do not see a reliable encoding detection procedure available on basic installation of python2.7. I made a version which ignores decoding errors.

@z25clp The following branch ignores decoding errors, try it out (click download zip, unpack and run `setup_win.bat`): 
https://github.com/sizmailov/textext/tree/hotfix/ignore_subprocess_decoding_errors

Installation script may complain about unknown versions of pstoedit/ghostscript but it's OK. 

If installer is unsure about your system skip requirements check: https://textext.github.io/textext/install/windows.html#windows-install-textext

**Comment by jcwinkler** [comment]
> First I used Textext 0.8.2,. The extension works, however the generated latex text does not appears in the inkscape document. How to solve that problem?

Often one thinks no output is produced but in reality it is put outside of the viewing area, espsecially if you hava an empty document which is zoomed outside of the center. So after generating the svg node please press the key `4` and you should see the output.

**Comment by z25clp** [comment]
I drew a line, then I use the tex text option, I write in the window $x^2$, I press preview and in the bottom of the window appears just x^2 like in pdf documment, however when I press "save", and I press the key 4, then in the inkscape document appears the following:
![g851](https://user-images.githubusercontent.com/46035466/50407442-e12fec00-07b5-11e9-9643-8af024543bda.png)

**Comment by sizmailov** [comment]
@z25clp Please follow the instructions from my previous comment. We need more information to investigate the issue.

**Comment by z25clp** [comment]
I had tried to following the advice; however , if the following steps are incorrect, please could you be more specific about the instructions? Sorry...

I downloaded the file "TexText-Windows-0.9.0.zip", then I unpacked it and I run setup_win.bat by doble click on it. The following appears:

````
Trying to find Inkscape...
Trying registry root HKLM...
Trying registry root HKCU...
Inkscape found as C:\Program Files\Inkscape\inkscape.exe

Trying to detect Python interpreter in Inkscape installation directory...
Success

Trying to run "C:\Program Files\Inkscape\\python.exe" setup.py --inkscape-executable="C:\Program Files\Inkscape\\inkscape.exe" ...

[TexText][INFO    ]: Using `inkscape-executable` = `C:\Program Files\Inkscape\\inkscape.exe`
Traceback (most recent call last):
  File "setup.py", line 332, in <module>
    check_result = checker.check()
  File "extension\textext/requirements_check.py", line 751, in check
    check_result = textext_requirements.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 477, in and_impl
    R = rhs.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 489, in or_impl
    L = self.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 476, in and_impl
    L = self.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 502, in invert_impl
    L = self.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 476, in and_impl
    L = self.check()
  File "extension\textext/requirements_check.py", line 423, in check
    result = self.criteria()
  File "extension\textext/requirements_check.py", line 413, in <lambda>
    self.criteria = lambda: criteria(*args, **kwargs)
  File "extension\textext/requirements_check.py", line 613, in find_pstoedit
    first_stderr_line = stderr.decode("utf-8").split("\n")[0]
  File "C:\Program Files\Inkscape\lib\python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 241: invalid continuation byte

Presione una tecla para continuar . . .
""

**Comment by z25clp** [comment]
I have to try install from the begining....

I unistall Inkscape, PyGtK2... pstoedit, goshtcript, ImagicMagic... except Miktex

I have followed the istructions in: https://textext.github.io/textext/install/windows.html#

The following message appears

```
Trying to find Inkscape...
Trying registry root HKLM...
Trying registry root HKCU...
Inkscape found as C:\Program Files\Inkscape\inkscape.exe

Trying to detect Python interpreter in Inkscape installation directory...
Success

Trying to run "C:\Program Files\Inkscape\\python.exe" setup.py --inkscape-executable="C:\Program Files\Inkscape\\inkscape.exe" ...

[TexText][INFO    ]: Using `inkscape-executable` = `C:\Program Files\Inkscape\\inkscape.exe`
[TexText][SUCCESS ]: + [Succ] TexText requirements
[TexText][SUCCESS ]: /-and-* [Succ] Detect inkscape
[TexText][SUCCESS ]: |      inkscape is found at `C:\Program Files\Inkscape\\inkscape.exe`
[TexText][SUCCESS ]: /-and-* [Succ] Detect `python2.7`
[TexText][SUCCESS ]: |      python2.7 is found at `C:\Program Files\Inkscape\python.exe`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect *latex
[TexText][SUCCESS ]: |     /--or-* [Succ] `pdflatex.exe` is found at `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `lualatex.exe` is found at `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: |     /--or-* [Succ] `xelatex.exe` is found at `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\`
[TexText][SUCCESS ]: /-and-+ [Succ] Detect GUI library
[TexText][SUCCESS ]: |     /--or-* [Succ] PyGTK2 is found
[TexText][SUCCESS ]: |     /--or-* [Succ] TkInter is found
[TexText][SUCCESS ]: /-and-+ [Succ] Detect pdf->svg conversion utility
[TexText][SUCCESS ]:       /--or-+ [Succ] Detect compatible pstoedit+ghostscript versions
[TexText][SUCCESS ]:       |     /-and-+ [Succ]
[TexText][INFO    ]:       |     |     /-not-+ [Fail] Detect incompatible versions of pstoedit+ghostscript
[TexText][INFO    ]:       |     |           /-and-* [Fail] pstoedit=3.70 is not found (but pstoedit=3.73 is found)
[TexText][INFO    ]:       |     |           /-and-* [Fail] ghostscript=9.22 is not found (but ghostscript=9.26 is found)
[TexText][SUCCESS ]:       |     /-and-* [Succ] pstoedit is found
[TexText][SUCCESS ]:       |     /-and-* [Succ] ghostscript is found
[TexText][SUCCESS ]:       /--or-* [Succ] Detect pdf2svg:
[TexText][SUCCESS ]:              `pdf2svg.exe` is found at `C:\Users\Rebollo\Documents\pdf2svg`
[TexText][INFO    ]: `textext/config.json` is not found in distribution, keep old file
[TexText][INFO    ]: Removing `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext`
[TexText][INFO    ]: Removing `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext.inx`
[TexText][INFO    ]: Creating directory `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext`
[TexText][INFO    ]: Copying `extension\textext\asktext.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\asktext.py`
[TexText][INFO    ]: Copying `extension\textext\default_packages.tex` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\default_packages.tex`
[TexText][INFO    ]: Copying `extension\textext\errors.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\errors.py`
[TexText][INFO    ]: Copying `extension\textext\errors.pyc` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\errors.pyc`
[TexText][INFO    ]: Creating directory `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\icons`
[TexText][INFO    ]: Copying `extension\textext\icons\logo-128x128.png` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\icons\logo-128x128.png`
[TexText][INFO    ]: Copying `extension\textext\icons\logo-16x16.png` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\icons\logo-16x16.png`
[TexText][INFO    ]: Copying `extension\textext\icons\logo-32x32.png` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\icons\logo-32x32.png`
[TexText][INFO    ]: Copying `extension\textext\icons\logo-64x64.png` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\icons\logo-64x64.png`
[TexText][INFO    ]: Copying `extension\textext\latexlogparser.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\latexlogparser.py`
[TexText][INFO    ]: Copying `extension\textext\requirements_check.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\requirements_check.py`
[TexText][INFO    ]: Copying `extension\textext\requirements_check.pyc` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\requirements_check.pyc`
[TexText][INFO    ]: Copying `extension\textext\textext.log` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\textext.log`
[TexText][INFO    ]: Copying `extension\textext\typesetter.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\typesetter.py`
[TexText][INFO    ]: Copying `extension\textext\utility.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\utility.py`
[TexText][INFO    ]: Copying `extension\textext\utility.pyc` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\utility.pyc`
[TexText][INFO    ]: Copying `extension\textext\win_app_paths.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\win_app_paths.py`
[TexText][INFO    ]: Copying `extension\textext\win_app_paths.pyc` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\win_app_paths.pyc`
[TexText][INFO    ]: Copying `extension\textext\__init__.py` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext\__init__.py`
[TexText][INFO    ]: Copying `extension\textext.inx` to `C:\Users\Rebollo\AppData\Roaming\inkscape\extensions\textext.inx`
[TexText][SUCCESS ]: --> TexText has been SUCCESSFULLY installed on your system <--

Presione una tecla para continuar . . .
"""

The I run Inkscape and I write $x^2$ the following appears after press preview:

![captura de pantalla 1](https://user-images.githubusercontent.com/46035466/50427258-d6428d80-0881-11e9-8acc-48f319881592.png)

and after save in the inkscape document appears the same as in my previous  comment.

I must say that the ImagicMagick has not installed. However in the instructions:  https://textext.github.io/textext/install/windows.html# does not say anyting about this package.

**Comment by sizmailov** [comment]
@z25clp You faced a bug in requirement check. I made a patch and asked you to test it. You altered your system (reinstalling packages, etc.) and now version without patch is working. So we don't have a confirmation from you that patch fixes the bug. 

As I understand something is wrong with your TeX compiler. It produces "pdftron" overlay. Follow instruction to confirm that:
https://textext.github.io/textext/usage/troubleshooting.html#trouble-manual-compile

**Comment by sizmailov** [comment]
@z25clp You faced a bug in requirement check. I made a patch and asked you to test it. You altered your system (reinstalling packages, etc.) and now version without patch is working. So we don't have a confirmation from you that patch fixes the bug. 

As I understand something is wrong with your TeX compiler. It produces "pdftron" overlay. Follow instruction to confirm that:
https://textext.github.io/textext/usage/troubleshooting.html#trouble-manual-compile

**Comment by jcwinkler** [comment]
Thank you for this feedback @LcDog. The fix is already in the develop branch now and I will shortly release an updated version.

**Comment by z25clp** [comment]
> 
> 
> @z25clp Thanks for testing. Can you upload `test.svg` too (the result of `pstoedit` conversion)?

I can't upload the test.svg file directly, I've to compress it. 
[test.zip](https://github.com/textext/textext/files/2712834/test.zip)

**Comment by sizmailov** [comment]
@jcwinkler In the `.svg` provided by @z25clp generated latex content has id="content". I was afraid it's different. The `pstoedit` pipeline should be fine. 

@z25clp Can you tell where "pdftron" overlay comes from?

**Comment by z25clp** [comment]
I

> 
>  
> @z25clp Can you tell where "pdftron" overlay comes from?

I don't have idea about it.... sorry.....

I recall that when I've installed the ImagicMagic in the "preview" of text ext window the result of the latex cod was good, however in the inkscape document appears this pdftron overlay...  After my last reinstallation of the text ext I don't install ImagicMagic I can try to see what happen....do you think is a good idea?

**Comment by jcwinkler** [comment]
This problem should be fixed now in [release 0.9.1](https://github.com/textext/textext/releases/tag/0.9.1)

**Comment by z25clp** [comment]
> 
> 
> This problem should be fixed now in [release 0.9.1](https://github.com/textext/textext/releases/tag/0.9.1)

I've donwloaded the new version "TexText-Windows-0.9.1.zip", then I unpackage it and I run setup_win.bat all was succeed. But my problem persists. :(

**Comment by sizmailov** [comment]
@z25clp Your `.pdf` and `.svg` are fine. I don't see how "pdftron" may appear. 

Do manual conversion of `.svg` to `png` using following command (you may need to specify full path to `inkcape` executable):
```bash
inkscape -f test.svg --export-png test.png  --export-id content --export-id-only --export-dpi=200
```

@jcwinkler Can you add `svg->png` conversion instructions to Troubleshooting section? 


@z25clp Please also attach the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows.

**Comment by z25clp** [comment]
> @z25clp Please also attach the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in `C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext` on Windows.

Here is the texttex.log:
[textext.zip](https://github.com/textext/textext/files/2714975/textext.zip)

**Comment by z25clp** [comment]
> @z25clp Your `.pdf` and `.svg` are fine. I don't see how "pdftron" may appear.
> 
> Do manual conversion of `.svg` to `png` using following command (you may need to specify full path to `inkcape` executable):
> 
> ```shell
> inkscape -f test.svg --export-png test.png  --export-id content --export-id-only --export-dpi=200
> ```

I've done. Now, the conversion is ok, but the resolution is low. After the command I've open the inkscape, I've import test.png and the result is:
![captura de pantalla 6](https://user-images.githubusercontent.com/46035466/50518074-82f35980-0a92-11e9-9cd7-116c80942dbf.png)

**Comment by z25clp** [comment]
Seems all was a foolish thing. I was looking about pdftron overlay... this is associated with pdf2svg program, so I look for this program on my system I found a directory with this name, I delete it and now all is ok.

![captura de pantalla 7](https://user-images.githubusercontent.com/46035466/50520585-049db400-0aa0-11e9-9ce5-b8b650862832.png)

**Comment by z25clp** [comment]
> 
> 
> @z25clp Please re-install textext and attach log file again. Log file must contain line similar to the following:
> 
> ```
> [2018-12-28 18:21:14,961][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.          //  __init__.py:140
> ```

I just run once setup_win from the textext-0.9.1 that I dowload yesterday, this is all? or I have to reinstall all packages from the beginning?

**Comment by sizmailov** [comment]
At first run TexText collects log in debug mode. Your log file does not contain such lines. You either attached wrong file or didn't run TexText after installation. 

The source of the problem seems to be more or less clear:
You have a custom `pdf2svg` program which produces the "pdftron" overlay. TexText prefers `pdf2svg` to `pstoedit` if finds both.

We would catch it at the beginning with `textext.log` at hands

**Comment by z25clp** [comment]
I'm trying to install the textext in inkscape in other laptop. I have followed the instuctions. I have the following error with pstoedit.exe

 "La aplicación no se pudo iniciar correctamente (0xc000007b). Haga clic en Aceptar para cerrarla"

Any help?

**Comment by z25clp** [comment]
The setup.log after run setup_win.bat from the 0.9.1 version of textext-windows
[setup.zip](https://github.com/textext/textext/files/2715905/setup.zip)

**Comment by sizmailov** [comment]
@z25clp All points to incorrect installation of requirements on target machine(s). Please carefully follow installation instructions. 

**The extension will NOT work if don't install all requirements correctly** 

It's really hard to help you since you do not follow precise instructions. You have been asked for one thing, but you keep doing something else without visible reason again and again. I'll try for the last time.

> @z25clp Please also attach the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in`C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext on Windows.`  Log file **MUST** contain line similar to the following: `[2018-12-28 18:21:14,961][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.`

**Comment by jcwinkler** [comment]
@sizmailov I updated the assets.

**Comment by z25clp** [comment]
> 
> 
> @z25clp All points to incorrect installation of requirements on target machine(s). Please carefully follow installation instructions.
> 
> **The extension will NOT work if you don't install all requirements correctly**
> 
> It's really hard to help you since you do not follow precise instructions. You have been asked for one thing, but you keep doing something else without visible reason again and again. I'll try for the last time.
> 
> > @z25clp Please also attach the TexText log file (since TexText 0.9.x). You find it in `~/.config/inkscape/extensions/textext` on Linux/ MacOS or in`C:\Users\[Your user name]\AppData\Roaming\inkscape\extensions\textext on Windows.`  Log file **MUST** contain line similar to the following: `[2018-12-28 18:21:14,961][DEBUG   ]: First run of TexText. Enforcing DEBUG mode.`

I'm trying to follow the instructions that you kindly give me...but perhaps I don't understand exactly you mean...I apologize for that... In relation with your last comment, I have done (as I understand) the following:

1. I download the TexText-Windows-0.9.1.zip (the las one from four day ago)

2. I extract it.
3. I run setup_win.bat
4. I went to C:....\AppData\Roaming\inkscape\extensions\textext 
5. I look for the TexText.log
6. I zip the file TextText.log

[textext.zip](https://github.com/textext/textext/files/2718934/textext.zip)

On the other hand... I have followed the instrucions: https://textext.github.io/textext/install/windows.html#windows-install-textext
However I don't undertand why the problem with the pstoedit file....

**Comment by z25clp** [comment]
In any case, On my computer the textext works....

@sizmailov and @jcwinkler  I whish you a happy new year 2019... a tank you so much.
